### ISSUE TITLE
Alt tab issues

### ISSUE THREAD

**Issue by selb** [jorisvddonk/system-reset#15] opened 2024-03-18 22:14 UTC
On Win11, if I alt-tab, I can no longer orient the camera with the mouse as expected. It is possible in this state to orient the camera by holding down a mouse button. Pressing Alt once after tabbing back in fixes it.

**Comment by jorisvddonk** [comment] 2024-03-18 22:25
The reason why the fix works is because Alt is mapped by default to the "cancel_mouse_capture" action in the input map. Changing the key binding to another key however reveals a new, slightly different problem; if you then focus back on the game window the mouse is captured but moving it won't work and you then still have to press whatever was bound to "cancel_mouse_capture".

A proper fix should entail responding to some kind of window focus event and then fixing the mouse capture.

**Comment by jorisvddonk** [comment] 2024-12-22 18:40
This has been fixed; I'm not sure when exactly (I think as part of the Godot 4.3 upgrade) but I can't reproduce it anymore in current main; closing.

**Closed by jorisvddonk** 2024-12-22 18:40 UTC
Labels: bug
